### ISSUE TITLE
Update url scheme

### ISSUE THREAD

**Issue by rocketinventor** [numberoverzero/brainfm#14]
Hi, I am so far a big fan of this project - It's working pretty well, nice job!

Everything seems to be working right now, except for the URL scheme is a little bit off... It seems that brain.fm updated there URL scheme from `https://stream.brain.fm/?tkn=[...]` to `https://stream2.brain.fm/?tkn=[...]` (at least for me).

Therefore, `https://stream2.brain.fm/?tkn=3ff0eab0-a5f6-11e6-a5c2-f11c700a6178` works, but `https://stream.brain.fm/?tkn=3ff0eab0-a5f6-11e6-a5c2-f11c700a6178` will give a 404.

**Comment by numberoverzero** [comment]
Thanks for opening an issue!  Glad it's working well so far.

I'm able to hear the same track (or as nearly as I can discern) at both of those urls.

Some guesses, in no particular order:
* They could be A/B testing (my IP can load `stream.brain.fm` but yours is in the test group)
* They were migrating infrastructure (serve from `stream2.brain.fm` while they re-deployed `stream.brain.fm` and it's back now)
* A deployment rollback (too many requests were 404ing on `stream.brain.fm`)

Regardless of current state, this is a good motivator to finally move the hardcoded endpoints into the stream client, so you could work around this on your side if it happens again.  That may require creating a Client instance in a few more places where we previously just used the "give me a url" functions.

**Comment by numberoverzero** [comment]
while testing, I hit the same problem.  However the `stream.brain.fm` version became available about 5 seconds after `stream2.brain.fm` did.  Could be a replication thing.  Either way, I'll have a change up soon and a version bump to 1.0.0

**Comment by rocketinventor** [comment]
Hi @numberoverzero. I updated the brainfm package last week after you closed this issue and I am still getting "https://stream.brain.fm/" URLs (which don't work) instead of "https://stream2.brain.fm" URLs (which do work).

I tried to make a new session to see if that fixed the issue, but it did not make any difference.

**Comment by rocketinventor** [comment]
So I did some poking around, and I determined that the usage of `stream` versus `stream2` in the URL is based on the value of the `'new-stream'` attribute (found in the `window.__FEATURES__` variable). A value of `true` would indicate to use the `stream2` version of the URL.

The formulation of the stream URL is based on this code (https://www.brain.fm/assets/app.bundle.js?v=1.0.844):
```javascript
[abridged for clarity]
function getStreamUrl(token) {
    [...]
  var baseUrl = (0, _feature.isEnabled)('new-stream') ? "https://stream2.brain.fm" : "https://stream.brain.fm";
    [...]
  return baseUrl + '/?tkn=' + token;
}
```

Relevant section within the HTML code (https://www1.brain.fm/app):
```javascript
[abridged for clarity]
        window.__FEATURES__ = {[...]"new-stream":true[...]};
```

**Comment by numberoverzero** [comment]
Thanks for continuing to look into this!  Sorry for the early closure, I didn't think there would be a way to deterministically select an endpoint.

I think parsing the html/app.bundle is starting to get fairly brittle, but since you've done the heavy lifting of identifying the strings, I'd be willing to add some parsing ;)

What do you think of the following changes:

1. `Connection.__init__` defaults `api_endpoint` and `stream_endpoint` to `None` and when a string isn't provided, calls `guess_{api,stream}_endpoint` to make a best-effort selection.  It would fall back to an array of known endpoints, to try and degrade when app.html or app.bundle break the parsing.
2. Expose a cli option `--stream-endpoint` and/or env variable `BRAINFM_STREAM_ENDPOINT` so that users can fix their endpoint without waiting for a new version of this package.

**Comment by rocketinventor** [comment]
Good news!

I found a better way to determine the endpoint URL! - There is no need to add any HTML parsing, data fetching, etc.

I made a small discovery that the `window.__FEATURES__` variable in the HTML is equivalent, exactly, to the 'features' attribute found in the response of `brainfm.Connection().login()`. All that needs to be done is to parse that response data (which we already have) and store the relevant info. As I said before, if `'new-stream'` is true then the URL will be of the `stream2` variety (as opposed to just `stream`). This value doesn't seem to change across sessions; the URL only needs to be determined once per user, not each time we generate a token.

This endpoint URL could also be exposed as an environment variable, etc. as you aptly suggested above. You could also write some heuristics to determine the endpoint URL's on-demand, and make those changes, but I don't think that is so necessary.

**Comment by numberoverzero** [comment]
Good call, here's the login response object:

```
{'message': 'You have been successfully logged in.',
 'user': {...},
 'subscription': {...},
 'trial': {...},
 'enterprise': {...},
 'consent': {...},
 'features': {
  ...,
  'new-stream': True,  // <-- use stream2 instead of stream
  ...
 }
}
```

For anyone that wants to inspect their own account, this comes from `Connection.login`:
```
>>> import brainfm
>>> conn = brainfm.Connection()
>>> conn.login("username", "password")
```

---

This is only helpful if the user is logging in through this instance, not if they're using a cached `sid` since we can't get the `features` object without posting to login.  If we lazy load the `stream_endpoint` then every cli operation that needs a stream url will be slow for users that don't set `BRAINFM_STREAM_ENDPOINT` or provide `--stream-endpoint`.  I'll go with it for now, and add a note to `brainfm init` encouraging users to set the stream_endpoint envvar for performance.

---
Rejected ideas:

A more robust solution would involve caching the user details object from `Connection.login` to disk and inspecting that during startup, but I'd prefer not to throw Yet-Another-Config-File into everyone's home directory.

Storing username/password in envvars would ensure we pass through Connection.login every time but this is terrible because password re-use is common and I don't want this tool to be anyone's root cause for a credentials leak.

**Comment by numberoverzero** [comment]
I've [released 2.0.0](https://pypi.org/project/brainfm/) with some breaking changes:

* environment variables are entirely constrained to the cli portion
* Connection lazy loads features where needed.
* `brain sid` was replaced with `brain details`:

```
> brain details
sid s%...
api https://www1.brain.fm
stream https://stream2.brain.fm
```

When you have time, can you please update and try things out?  I wouldd re-run `brain init` at least.

**Comment by rocketinventor** [comment]
Thank you, I tested it out a little bit in the CLI mode, and from within Python, also. So far the changes have been working exactly as they should.

It seems like the "library" version is scraping the site the first time we try to generate a URL, and then saving the base URL as a local variable for re-use, and it's doing this each time the script is run - no matter what. Is that correct?

---

I agree both on the point having about not having another config file and also about not storing the credentials in plaintext. It's worth noting, though, that there are many projects out there that work on a hybrid CLI parameters/config file setup (configuration is stored somewhere as an optional `.json` file and is overridden by CLI parameters); over time, having a large collection of env vars is not so great, either.

**Comment by numberoverzero** [comment]
Great point about limiting env variables; if there are more feature requests I'll look first at a config file, since three already feels like a lot to devote to such a focused tool.

Let me know if there's additional work here, otherwise I'll close this at some point.  Thanks again for the help and feedback!

---

I think you've got the order correct.  For my own reference (and the next user that has the same question) I wrote out the full priority below.

The stream endpoint for a given connection is determined as follows:

1. If one is provided during [`Connection.__init__`](https://github.com/numberoverzero/brainfm/blob/f17def2a9f625835beaa6259f34844ae7d757cfe/brainfm/__init__.py#L47) that is always used
2. Else if [`Connection.login`](https://github.com/numberoverzero/brainfm/blob/f17def2a9f625835beaa6259f34844ae7d757cfe/brainfm/__init__.py#L90) is called and it is not already defined, one is parsed from the `features` response object
3. Else if the [`Connection.stream_endpoint`](https://github.com/numberoverzero/brainfm/blob/f17def2a9f625835beaa6259f34844ae7d757cfe/brainfm/__init__.py#L71-L72) property is accessed and is not already defined, [fall back to parsing](https://github.com/numberoverzero/brainfm/blob/f17def2a9f625835beaa6259f34844ae7d757cfe/brainfm/__init__.py#L134-L140) `https://www1.brain.fm/app` html.

The connection class doesn't look for env vars, so it's either (1) at init (2) from login (3) parse if not defined.

The cli exposes options to provide the stream endpoint, passed to `Connection.__init__`:

1. If [provided on the command line](https://github.com/numberoverzero/brainfm/blob/f17def2a9f625835beaa6259f34844ae7d757cfe/brainfm/main/cli.py#L30) as `brain --stream-endpoint=https://my.proxy:8080 play 512`
2. Else if an [env var](https://github.com/numberoverzero/brainfm/blob/f17def2a9f625835beaa6259f34844ae7d757cfe/brainfm/main/cli.py#L14) is defined `BRAINFM_STREAM_ENDPOINT=https://my.proxy:8080 brain play 512`

So the full priority order from the cli's perspective is (first wins):

1. `-stream-endpoint=`
2. `BRAINFM_STREAM_ENDPOINT`
3. Feature flags during `brain init` (calls Connection.login)
4. Fall back to parsing html

**Comment by rocketinventor** [comment]
Ok, thank you for making the implementation, and also for re-writing this.

For the library version, though, are you going to bring back the ability to manually set the `stream` and `API` endpoints? – Something like the CLI `-stream-endpoint=`, but as part of the function call? You noted before that the last update “broke” the ability to set this manually (in Python)…

I think we can call this issue closed once this functionality is restored. – It’s basically resolved at this point.

**Comment by numberoverzero** [comment]
I think your copy/paste may be off :)

`Connection` properties `api_endpoint` and `stream_endpoint` can be set at any time, including init.  These properties never went away, so I may be misunderstanding the question.

```python
import brainfm
conn = brainfm.Connection()

# has default value
print(conn.api_endpoint)

# asking for stream_endpoint property now will parse html since this
# instance hasn't logged in or been given an explicit value
print(conn.stream_endpoint)

# set both directly
conn.api_endpoint = "http://localhost:8080"
conn.stream_endpoint = "http://localhost:8081"

# since we've manually set stream_endpoint just now, login() won't overwrite the value
conn.login("proxy_user", "proxy_pass")

assert conn.stream_endpoint == "http://localhost:8081"
```

**Comment by rocketinventor** [comment]
Ok, thanks for that catch. The issue that I meant to address was the part about the "environment variables [being] constrained to the CLI portion". I had it mixed up on which features were actually removed. I didn't see it in the documentation, either, so that did not help - maybe update [the PyPI docs](https://pypi.org/project/brainfm)?

CLI variables are not so necessary for Python scripting, so I think that this issue is resolved. They are, however, convenient. Also, they help keep the library and CLI versions in sync. Is there any plan on bringing them back to this project?

**Comment by numberoverzero** [comment]
I'd like to keep environment variables out of the Connection class, it shouldn't care how a user configures parameters.  I wrote a snippet below that can be used to pull from the same envvars.  It's not specific to this library though, just the usual `os.environ.get` mechanism.

If there are additional uses for feature flags, I'd consider adding a `Connection.features` dict that lazy-loads using the existing method, and leave the two endpoints + sid as manual overrides.  But for now there's not much use for everything the website puts in that dict.

---

### Loading endpoints from environment variables

```python
import brainfm

def connection_with_env() -> brainfm.Connection:
    import os
    import brainfm.main.cli as cli
    get = os.environ.get
    
    return brainfm.Connection(
        sid=get(cli.ENVKEY_SID),
        api_endpoint=get(cli.ENVKEY_API_ENDPOINT),
        stream_endpoint=get(cli.ENVKEY_STREAM_ENDPOINT))
```
