### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Danielhiversen** [numberoverzero/brainfm#3]
Thanks for making this library.

Have you tested it with python 3.4?
I am getting this error while importing the library

```
In [1]: import brainfm
  File "/home/daniel/home-assistant/venv/lib/python3.4/site-packages/brainfm/__init__.py", line 75
    **wire_kwargs,
     ^
SyntaxError: invalid syntax

```

**Comment by numberoverzero** [comment]
I haven't tested with 3.4, but that is the new [dict unpacking](https://www.python.org/dev/peps/pep-0448/#id6) from 3.5.

I don't think 3.4 is too much work to support, I'll give it a shot.

**Comment by numberoverzero** [comment]
I was a bit optimistic.  There are three issues with the existing library:

1. `{**dict}` unpacking
2. `pathlib.Path.expanduser` doesn't exist
3. `pathlib.Path.mkdir` doesn't have an `exist_ok` param

I'm planning to use [f strings](https://www.python.org/dev/peps/pep-0498/) in 3.6 since 3.6.0rc1 is out, which would further split the code base.

I haven't given this project much attention lately (there are a number of unresolved/broken commands) because `ls` and `play` have been sufficient -- I'd rather implement the remaining commands first.  If you want to create a fork for 3.4, I'm happy to open a PR with the necessary changes.  For now though, I'm going to keep it on 3.5 (soon 3.6).

Let me know if you'd like me to send over the changes.  Sorry that this won't support 3.4 right now.

**Comment by Danielhiversen** [comment]
Ok, thanks. Guess it is time to upgrade to 3.5.
I would suggest that you add required python version to the readme file

**Comment by numberoverzero** [comment]
Done!  Thanks for opening an issue.

If you upgrade to 3.5, feel free to open an issue for functionality you'd like.  It does what I set out to do, but I don't mind implementing additional features for others.
